### ISSUE TITLE
One way to set number of characters per typing.

### ISSUE THREAD

**Issue by davidsonfellipe** [davidsonfellipe/im-coder#16]
Currently is 5chars/keydown!

**Comment by jigar1101** [comment]
@davidsonfellipe Can you check #28

**Comment by khorramk** [comment]
can i contribute?

**Comment by davidsonfellipe** [comment]
@jigar1101 checked, thanks!

**Comment by davidsonfellipe** [comment]
@khorramk sure, you can! Send the suggestion as an issue.
